<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>vip.geekclub</groupId>
    <artifactId>service</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>service</name>
    <description>arc</description>
    <modules>
        <module>starter</module>
        <module>infrastructure</module>
        <module>context.security</module>
        <module>context.manager</module>
        <module>context.internship</module>
    </modules>
    <properties>
        <java.version>21</java.version>
        <querydsl.version>5.1.0</querydsl.version>
    </properties>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.1</version>
        <relativePath/>
    </parent>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>
        <!-- Jackson dependencies -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>it.ozimov</groupId>
                    <artifactId>yaml-properties-maven-plugin</artifactId>
                    <version>1.1.3</version>
                    <executions>
                        <execution>
                            <phase>generate-resources</phase>
                            <goals>
                                <goal>read-project-properties</goal>
                            </goals>
                            <configuration>
                                <files>
                                    <!-- 读取子模块的YAML配置文件 -->
                                    <file>${project.basedir}/../starter/src/main/resources/application-dev.yml</file>
                                </files>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <!--JOOQ代码生成插件-->
                <plugin>
                    <groupId>org.jooq</groupId>
                    <artifactId>jooq-codegen-maven</artifactId>
                    <executions>
                        <execution>
                            <phase>generate-resources</phase>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <jdbc>
                            <!--suppress UnresolvedMavenProperty -->
                            <driver>${config.database.driver-name}</driver>
                            <!--suppress UnresolvedMavenProperty -->
                            <url>${config.database.url}</url>
                            <!--suppress UnresolvedMavenProperty -->
                            <user>${config.database.username}</user>
                            <!--suppress UnresolvedMavenProperty -->
                            <password>${config.database.password}</password>
                        </jdbc>
                        <generator>
                            <database>
                                <name>org.jooq.meta.mysql.MySQLDatabase</name>
                                <!--suppress UnresolvedMavenProperty -->
                                <inputSchema>${config.database.name}</inputSchema>
                            </database>
                            <generate>
                                <records>false</records>
                                <interfaces>true</interfaces>
                                <pojos>true</pojos>
                                <fluentSetters>true</fluentSetters>
                                <javaTimeTypes>true</javaTimeTypes>
                                <immutablePojos>true</immutablePojos>
                                <serializablePojos>true</serializablePojos>
                            </generate>
                            <strategy>
                                <matchers>
                                    <tables>
                                        <table>
                                            <expression>.*?_(.*)$</expression>
                                            <tableIdentifier>
                                                <transform>PASCAL</transform>
                                                <expression>$1</expression>
                                            </tableIdentifier>
                                            <tableClass>
                                                <transform>PASCAL</transform>
                                                <expression>$1_Table</expression>
                                            </tableClass>
                                            <pojoClass>
                                                <transform>PASCAL</transform>
                                                <expression>$1_Dto</expression>
                                            </pojoClass>
                                        </table>
                                    </tables>
                                </matchers>
                            </strategy>
                        </generator>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>