spring:
  jmx:
    enabled: false
  application:
    name: arc
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      Jakarta:
        persistence:
          validation:
            mode: none
      hibernate:
        generate_statistics: false
        boot:
#          allow_jdbc_metadata_access: false
        validator:
          autoregister_listeners: false
        jdbc:
          batch_size: 20
        format_sql: true
        hbm2ddl:
          auto: none

  data:
    redis:
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: true
    jdbc:
      repositories:
        enabled: false

server:
  servlet:
    context-path: /api
